site_name: axion-release-plugin
site_description: Gradle release & version mamangement plugin.
site_author: allegro.tech

repo_url: https://github.com/allegro/axion-release-plugin
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      anchorlink: true

nav:
  - Home: 'index.md'
  - Changelog: 'https://github.com/allegro/axion-release-plugin/releases'
  - Examples: 'examples/examples.md'
  - Configuration:
    - Overview: 'configuration/overview.md'
    - Basic usage: 'configuration/basic_usage.md'
    - Tasks: 'configuration/tasks.md'
    - Version creation: 'configuration/version.md'
    - Repository: 'configuration/repository.md'
    - Authorization: 'configuration/authorization.md'
    - Overriding version: 'configuration/force_version.md'
    - Next version markers: 'configuration/next_version.md'
    - Pre/post release hooks: 'configuration/hooks.md'
    - Pre-release checks: 'configuration/checks.md'
    - Uncommitted changes: 'configuration/uncommitted_changes.md'
    - Publishing: 'configuration/publishing.md'
    - Dry run: 'configuration/dry_run.md'
    - CI Servers: 'configuration/ci_servers.md'
    - Resolving dependency conflicts: 'configuration/resolving_dependency_conflicts.md'
    - Extensions: 'configuration/extensions.md'
